### PR TITLE
Boss secretary module updated

### PR DESCRIPTION
**Pull request by ghost**
New updated version with changed functionality:

The boss-secretary module creates a special **ring group** which includes
one or more "bosses" and one or more secretaries". When someone calls
the boss' extension, the secretary (or secretaries) extension will ring only, 
allowing the secretary to answer his or her boss' call.

The module generates the appropriate hints to have ip phones show the 
groups state by subscribing to the *152<ext number> extension.

### CODE REVIEW

**Comment by tm1000** [comment]
http://wiki.freepbx.org/display/DC/Code+License+Agreement

**Comment by tm1000** [comment]
Please sign said agreement so that we can include this code.

**Comment by ghost** [comment]
Dear Sangoma Technologies Corporation,

I'm sending signed FreePBX Code Submission Agreement in attachment.

Yours faithfully,
David Hrbaty

**Comment by tm1000** [comment]
Thanks for the patch and code agreement much appreciated!

**Comment by tm1000** [comment]
Patch applied. Let me know if you want it to show up in the online repository under "unsupported" (which will in turn give it a code signature)

**Comment by ghost** [comment]
Hi Andrew,

It will be great. I want to show up in the online repository under
"unsupported" modules.

Thank you

**Pull request merged**
